name: labeled issue auto move

on:
  issues:
    types: [labeled]

jobs:
  Move_Labeled_Issue_On_Project_Board:
    runs-on: ubuntu-latest
    steps:
    - name: Move bug ready to the Bug column
      uses: konradpabjan/move-labeled-or-milestoned-issue@v2.0
      with:
        project-url: "https://github.com/linzhou-zhong/github_action_auto_move/projects/1"
        label-name: "bug"
        column-name: "Bug"
        action-token: "${{ secrets.ACTION_SECRET }}"

    - name: Move question ready to the Question column
      uses: konradpabjan/move-labeled-or-milestoned-issue@v2.0
      with:
        project-url: "https://github.com/linzhou-zhong/github_action_auto_move/projects/1"
        label-name: "question"
        column-name: "Question"
        columns-to-ignore: "Bug"
        action-token: "${{ secrets.ACTION_SECRET }}"

    - name: Remove ticket
      uses: justgiveacar/move-labeled-or-milestoned-issue@v3.0
      with:
        project-url: "https://github.com/linzhou-zhong/github_action_auto_move/projects/1"
        label-name: "done"
        delete-card: "true"
        action-token: "${{ secrets.ACTION_SECRET }}"

    - name: Move to new project
      uses: konradpabjan/move-labeled-or-milestoned-issue@v2.0
      with:
        project-url: "https://github.com/linzhou-zhong/github_action_auto_move/projects/2"
        label-name: "done"
        column-name: "Done"
        action-token: "${{ secrets.ACTION_SECRET }}"

