name: labeled issue auto move

on:
  issues:
    types: [labeled]

jobs:
  Move_Labeled_Issue_On_Project_Board:
    runs-on: ubuntu-latest
    steps:
    - name: Move meta ready to the Ready column
      uses: konradpabjan/move-labeled-or-milestoned-issue@v2.0
      with:
        project-url: "https://github.com/linzhou-zhong/github_action_auto_move/projects/1"
        label-name: "bug"
        column-name: "Bug"
        action-token: "${{ secrets.ACTION_SECRET }}"

    - name: Move meta ready to the Ready column
      uses: konradpabjan/move-labeled-or-milestoned-issue@v2.0
      with:
        project-url: "https://github.com/linzhou-zhong/github_action_auto_move/projects/1"
        label-name: "question"
        column-name: "Question"
        columns-to-ignore: "Bug"
        action-token: "${{ secrets.ACTION_SECRET }}"

    - name: Move to new project
      uses: konradpabjan/move-labeled-or-milestoned-issue@v2.0
      with:
        project-url: "https://github.com/linzhou-zhong/github_action_auto_move/projects/2"
        label-name: "done"
        column-name: "Done"
        action-token: "${{ secrets.ACTION_SECRET }}"

    - name: Remove ticket
      uses: alex-page/github-project-automation-plus@v0.8.1
      with:
        project: "Backlog"
        column: "Done"
        action: "delete"
        repo-token: "${{ secrets.ACTION_SECRET }}"