name: labeled issue auto move

on:
  issues:
    types: [labeled]

jobs:
  Move_Labeled_Issue_On_Project_Board:
    runs-on: ubuntu-latest
    steps:
    - name: Move meta ready to the Ready column
      uses: konradpabjan/move-labeled-or-milestoned-issue@v2.0
      with:
        project-url: "https://github.com/linzhou-zhong/github_action_auto_move/projects/1"
        label-name: "bug"
        column-name: "Bug"
        action-token: "${{ secrets.ACTION_SECRET }}"

    - name: Move meta ready to the Ready column
      uses: konradpabjan/move-labeled-or-milestoned-issue@v2.0
      with:
        project-url: "https://github.com/linzhou-zhong/github_action_auto_move/projects/1"
        label-name: "question"
        column-name: "Ready"
        columns-to-ignore: "Bug"
        action-token: "${{ secrets.ACTION_SECRET }}"

    - name: Remove ticket
      uses: pauldruziak/move-labeled-or-milestoned-pull-request@v1.0.2
      with:
        action-token: "${{ secrets.ACTION_SECRET }}"
        project-url: "https://github.com/linzhou-zhong/github_action_auto_move/projects/1"
        column-name: "Bug"
        label-name: "bug"
        delete-card: "true"

    - name: Move to new project
      uses: konradpabjan/move-labeled-or-milestoned-issue@v2.0
      with:
        project-url: "https://github.com/linzhou-zhong/github_action_auto_move/projects/2"
        label-name: "bug"
        column-name: "Bug"
        action-token: "${{ secrets.ACTION_SECRET }}"